// Generated by CoffeeScript 1.12.7
(function() {
  var PDFOutline;

  PDFOutline = require('../outline');

  module.exports = {
    initOutline: function() {
      return this.outline = new PDFOutline(this, null, null, null);
    },
    endOutline: function() {
      this.outline.endOutline();
      if (this.outline.children.length > 0) {
        this._root.data.Outlines = this.outline.dictionary;
        return this._root.data.PageMode = 'UseOutlines';
      }
    }
  };

}).call(this);
